import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const logistic=x=>1/(1+Math.pow(10,-x/400));
const won=(m,id)=>typeof m.won==="boolean"?m.won:(String(m.winner_id??m.winner?.id)===String(id));
function profile(rows,id,surface){const completed=rows.filter(m=>typeof m.won==="boolean"||m.status==="finished"||m.winner_id||m.winner_name);const last=completed.slice(0,20),surf=last.filter(m=>String(m.surface||"").toLowerCase()===String(surface||"").toLowerCase());const rate=x=>x.length?x.filter(m=>won(m,id)).length/x.length:.5;return{n:last.length,wins:rate(last),surfaceN:surf.length,surfaceWins:rate(surf),form:rate(last.slice(0,8))}}
function model(f,h){if(!f||!h.p1?.length||!h.p2?.length)return null;const A=profile(h.p1,f.player1_id,f.surface),B=profile(h.p2,f.player2_id,f.surface);const sample=Math.min(1,Math.min(A.n,B.n)/20),overall=220*(A.wins-B.wins)*sample,surfaceSample=Math.min(1,(A.surfaceN+B.surfaceN)/20),surface=90*(A.surfaceWins-B.surfaceWins)*surfaceSample,form=70*(A.form-B.form)*sample,d=overall+surface+form,p=logistic(d);return{A,B,p,factors:[["Recent win rate",overall],["Surface adjustment",surface],["Recent form",form]],confidence:Math.min(1,(A.n+B.n)/40)*Math.min(1,(A.surfaceN+B.surfaceN+6)/18)}}
function Bar({v}){return <div className="bar"><i style={{width:v*100+"%"}}/></div>}
function App(){const[fixtures,setFixtures]=useState([]),[dataStatus,setDataStatus]=useState("Laddar riktiga matcher…"),[selectedFixture,setSelectedFixture]=useState(null),[history,setHistory]=useState({});
useEffect(()=>{fetch("/api/fixtures").then(async r=>{const j=await r.json();if(!r.ok)throw Error();const rows=Array.isArray(j.data)?j.data:[];setFixtures(rows.slice(0,12));setDataStatus(rows.length?`${rows.length} singelmatcher hittade`:"Inga singelmatcher hittades")}).catch(()=>setDataStatus("Kunde inte läsa matchdata"))},[]);
useEffect(()=>{if(!selectedFixture)return;setHistory({});Promise.all([selectedFixture.player1_id,selectedFixture.player2_id].map(id=>fetch("/api/player-history?name="+encodeURIComponent(id===selectedFixture.player1_id?selectedFixture.player1_name:selectedFixture.player2_name)+"&tour="+encodeURIComponent(selectedFixture.tour||"atp")).then(r=>r.json()))).then(([x,y])=>setHistory({p1:x.data||[],p2:y.data||[]})).catch(()=>setHistory({p1:[],p2:[]}))},[selectedFixture]);
const m=useMemo(()=>model(selectedFixture,history),[selectedFixture,history]);const usable=!!m&&m.A.n>=8&&m.B.n>=8;
return <main><header><b>TENNIS<span>AI</span></b><small>PRE-MATCH MODEL • v0.3</small></header>
<section className="card"><h2>Kommande singelmatcher</h2><div className="stat"><span>Live Tennis API</span><b>{dataStatus}</b></div>{fixtures.map((x,i)=><button type="button" className="stat fixture" key={x.id||i} onClick={()=>setSelectedFixture(x)}><span>{x.player1_name} vs {x.player2_name}<small>{x.tournament} • {x.status==="scheduled"?"KOMMANDE":x.status==="live"?"LIVE":"AVSLUTAD"}</small></span><b>{x.surface}</b></button>)}</section>
{selectedFixture&&<><section className="card hero"><h2>Matchanalys</h2><div className="prob"><strong>{selectedFixture.player1_name}</strong><em>VS</em><strong>{selectedFixture.player2_name}</strong></div><p className="note">{selectedFixture.tournament} • {selectedFixture.round} • {selectedFixture.surface} • {new Date(selectedFixture.start_time).toLocaleString("sv-SE",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</p><div className="stat"><span>Historik laddad</span><b>{history.p1?.length||0} / {history.p2?.length||0} matcher</b></div></section>
{m&&!usable&&<section className="card"><h2>Otillräcklig historik</h2><div className="stat"><span>Spelare 1</span><b>{m.A.n} matcher</b></div><div className="stat"><span>Spelare 2</span><b>{m.B.n} matcher</b></div><p className="disclaimer">Ingen modellprocent visas. Minst 8 användbara historiska matcher per spelare krävs för analys.</p></section>}{m&&usable&&<><section className="card hero"><h2>Första datamodellen</h2><div className="prob"><strong>{selectedFixture.player1_name}<big>{(m.p*100).toFixed(1)}%</big></strong><strong>{selectedFixture.player2_name}<big>{((1-m.p)*100).toFixed(1)}%</big></strong></div><Bar v={m.p}/><p className="note">Experimentell sportanalys från historiska matchresultat – ännu inte kalibrerad.</p></section>
<section className="grid"><div className="card"><h2>Spelare 1</h2><div className="stat"><span>Senaste matcher</span><b>{m.A.n}</b></div><div className="stat"><span>Vinstfrekvens</span><b>{(m.A.wins*100).toFixed(0)}%</b></div><div className="stat"><span>{selectedFixture.surface}</span><b>{(m.A.surfaceWins*100).toFixed(0)}% ({m.A.surfaceN})</b></div></div><div className="card"><h2>Spelare 2</h2><div className="stat"><span>Senaste matcher</span><b>{m.B.n}</b></div><div className="stat"><span>Vinstfrekvens</span><b>{(m.B.wins*100).toFixed(0)}%</b></div><div className="stat"><span>{selectedFixture.surface}</span><b>{(m.B.surfaceWins*100).toFixed(0)}% ({m.B.surfaceN})</b></div></div></section>
<section className="card"><h2>Varför?</h2>{m.factors.map(([n,v])=><div className="stat" key={n}><span>{n}</span><b>{v>0?"+":""}{v.toFixed(1)} {v>0?selectedFixture.player1_name:v<0?selectedFixture.player2_name:""}</b></div>)}<div className="stat"><span>Datatäckning</span><b>{(m.confidence*100).toFixed(0)}%</b></div><p className="disclaimer">Detta är v0.3 av analysmotorn. Historiken används endast som utvecklingsdata och källans villkor är icke-kommersiella. Innan en kommersiell version krävs en separat licensierad datakälla. Vinstfrekvensen är baslinjen och viktas nu även efter datamängd. Underlag och form är mindre justeringar för att minska dubbelräkning. Nästa steg är opponent-adjusted Elo.</p></section></>}</>}
{!selectedFixture&&<section className="card"><p className="disclaimer">Välj en riktig match ovan för att starta analysen.</p></section>}</main>}
createRoot(document.getElementById("root")).render(<App/>);