const MANIFEST="https://stats.tennismylife.org/api/data-files";
function csv(line){let a=[],s="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){s+='"';i++}else q=!q}else if(c===","&&!q){a.push(s);s=""}else s+=c}a.push(s);return a}
const prob=d=>1/(1+Math.pow(10,-d/400));
function calc(text){const lines=text.split(/\r?\n/).filter(Boolean),h=csv(lines[0]),ix=x=>h.indexOf(x),rows=[];for(const line of lines.slice(1)){const v=csv(line),w=v[ix("winner_name")],l=v[ix("loser_name")],surface=(v[ix("surface")]||"unknown").toLowerCase();if(w&&l)rows.push({date:v[ix("tourney_date")],w,l,surface})}rows.sort((a,b)=>String(a.date).localeCompare(String(b.date)));
const elo=new Map(),surf=new Map(),seen=new Map(),recent=new Map(),samples=[];const get=(m,k)=>m.get(k)??1500,set=(m,k,v)=>m.set(k,v);
for(const x of rows){const sw=seen.get(x.w)||0,sl=seen.get(x.l)||0,ew=get(elo,x.w),el=get(elo,x.l),sk=x.surface+"|",esw=get(surf,sk+x.w),esl=get(surf,sk+x.l);if(sw>=8&&sl>=8){const wf=String(x.w).localeCompare(String(x.l))<=0,a=wf?x.w:x.l,b=wf?x.l:x.w,ea=wf?ew:el,eb=wf?el:ew,esa=wf?esw:esl,esb=wf?esl:esw,y=wf?1:0,ra=recent.get(a)||[],rb=recent.get(b)||[],fa=ra.length?ra.reduce((s,z)=>s+z,0)/ra.length:.5,fb=rb.length?rb.reduce((s,z)=>s+z,0)/rb.length:.5;samples.push({date:x.date,dE:ea-eb,dS:esa-esb,dF:fa-fb,y})}const e=prob(ew-el),k=sw<20||sl<20?32:20;set(elo,x.w,ew+k*(1-e));set(elo,x.l,el-k*(1-e));const se=prob(esw-esl),ks=28;set(surf,sk+x.w,esw+ks*(1-se));set(surf,sk+x.l,esl-ks*(1-se));recent.set(x.w,[...(recent.get(x.w)||[]),1].slice(-8));recent.set(x.l,[...(recent.get(x.l)||[]),0].slice(-8));seen.set(x.w,sw+1);seen.set(x.l,sl+1)}
const cut=Math.max(1,Math.floor(samples.length*.7)),train=samples.slice(0,cut),test=samples.slice(cut),score=(arr,w)=>{let b=0,l=0;for(const s of arr){const p=Math.min(.999,Math.max(.001,prob(w.e*s.dE+w.s*s.dS+w.f*55*s.dF)));b+=(p-s.y)**2;l-=s.y*Math.log(p)+(1-s.y)*Math.log(1-p)}return{n:arr.length,brier:arr.length?b/arr.length:null,logloss:arr.length?l/arr.length:null}};
let best=null;for(const e of [.5,.65,.8,1])for(const s of [0,.15,.3,.45])for(const f of [0,.5,1]){const w={e,s,f},z=score(train,w);if(!best||z.logloss<best.train.logloss)best={weights:w,train:z}}
const holdout=score(test,best.weights),baseline=score(test,{e:1,s:0,f:0}),bins=Array.from({length:10},()=>({n:0,p:0,y:0}));for(const s of test){const p=Math.min(.999,Math.max(.001,prob(best.weights.e*s.dE+best.weights.s*s.dS+best.weights.f*55*s.dF))),bi=Math.min(9,Math.floor(p*10));bins[bi].n++;bins[bi].p+=p;bins[bi].y+=s.y}
return{n:test.length,brier:holdout.brier,logloss:holdout.logloss,benchmark:{name:"Overall Elo only",brier:baseline.brier,logloss:baseline.logloss},optimization:{split:"70% train / 30% holdout",trainN:train.length,testN:test.length,weights:best.weights,train:best.train,holdout,baseline},bins:bins.filter(b=>b.n).map(b=>({n:b.n,p:b.p/b.n,actual:b.y/b.n}))}}
export default async function handler(req,res){try{const tour=String(req.query?.tour||"atp").toLowerCase(),mr=await fetch(MANIFEST),m=await mr.json(),files=Array.isArray(m.files)?m.files:[],wanted=tour.includes("wta")?"2026_wta.csv":tour.includes("challenger")?"2026_challenger.csv":"2026.csv",f=files.find(x=>x.name===wanted);if(!f?.url)return res.status(404).json({error:"dataset unavailable"});const r=await fetch(f.url);if(!r.ok)throw Error("dataset fetch failed");const out=calc(await r.text());res.setHeader("Cache-Control","s-maxage=21600, stale-while-revalidate=3600");res.status(200).json({...out,dataset:wanted,method:"walk-forward",license:"non-commercial development only"})}catch(e){res.status(502).json({error:e.message||"backtest failed"})}}